#ifndef PROTOCOL_H
#define PROTOCOL_H

#define CMD_REGISTER        "REGISTER"
#define CMD_LOGIN           "LOGIN"

#define CMD_CREATE_PROJECT  "CREATE_PROJECT"
#define CMD_INVITE_MEMBER   "INVITE_MEMBER"

#define CMD_CREATE_TASK     "CREATE_TASK"
#define CMD_ASSIGN_TASK     "ASSIGN_TASK"

#define CMD_LIST_PROJECT    "LIST_PROJECT"
#define CMD_LIST_TASK       "LIST_TASK"

#endif
